FROM debian:stretch-slim

RUN apt-get update \
    && apt-get install --no-install-recommends --no-install-suggests -y \
        gnupg1 \
        ca-certificates \
    && apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 \
                   --keyserver-options timeout=10 \
                   --recv-keys 61E0A086749E463EDE502255CAEB3DC3BDF7FB45 \
    && echo "deb http://qgis.org/debian stretch main" >> /etc/apt/sources.list.d/qgis.list \
    && apt-get update \
    && apt-get install --no-install-recommends --no-install-suggests -y \
        xauth \
        xvfb \
        spawn-fcgi \
        qgis-server \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -m qgis

ENV TINI_VERSION v0.17.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini

ENV QGIS_PREFIX_PATH /usr
ENV QGIS_SERVER_LOG_FILE /var/log/qgisserver.log
ENV QGIS_SERVER_LOG_LEVEL 0
ENV QGIS_DEBUG 1

USER qgis
WORKDIR /home/qgis

CMD ["/tini", "--", "xvfb-run", \
     "spawn-fcgi", "-p", "5555", "-n", "-d", "/home/qgis", \
     "/usr/lib/cgi-bin/qgis_mapserv.fcgi"]
