version: '2'
services:
  nginx:
    image: nginx:1.13
    network_mode: host
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - ./map.html:/usr/share/nginx/html/index.html:ro
    depends_on:
    - qgis-exec
  qgis-exec:
    image: qgis-exec:latest
    network_mode: host
    volumes:
    - ./data:/data:ro
    environment:
    - QGIS_PROJECT_FILE=/data/osm.qgs
    - QGIS_SERVER_LOG_LEVEL=0  # INFO (log all requests)
    - PROCESSES=1
    - DEBUG=1                  # display env before spawning QGIS Server
