FROM debian:stretch-slim

RUN apt-get update \
    && apt-get install --no-install-recommends --no-install-suggests -y \
        gnupg1 \
        ca-certificates \
    && apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 \
                   --keyserver-options timeout=10 \
                   --recv-keys 61E0A086749E463EDE502255CAEB3DC3BDF7FB45 \
    && echo "deb http://qgis.org/debian stretch main" >> /etc/apt/sources.list.d/qgis.list \
    && apt-get update \
    && apt-get install --no-install-recommends --no-install-suggests -y \
        multiwatch \
        qgis-server \
        qgis \
        spawn-fcgi \
        xauth \
        xvfb \
    && rm -rf /var/lib/apt/lists/*

ENV TINI_VERSION v0.17.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini

ENTRYPOINT ["/tini", "--"]

CMD ["/usr/bin/qgis"]
